on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  run-daily-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pandas and Requests
        run: pip install pandas requests

      - name: Execute Script
        env:
          API_KEY: ${{ secrets.UPSTOX_API_KEY }}
          API_SECRET: ${{ secrets.UPSTOX_API_SECRET }}
        run: python get_nifty_keys.py

      - name: Update Repository File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add nifty50_upstox_keys.csv
          git commit -m "Auto-update Nifty keys" || exit 0
          git push
